/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package contest;

import static java.lang.System.out;

import java.util.Base64;
import java.util.Arrays;

import org.linkerdesign.crypto.abstraction.AesKeySize;
import org.linkerdesign.crypto.abstraction.EncodingType;
import org.linkerdesign.crypto.symmetricencryptdecrypt.Aes;

import org.linkerdesign.crypto.messagedigest.Md5;
import org.linkerdesign.crypto.messagedigest.Md5Sha1;
import org.linkerdesign.crypto.messagedigest.Sha1;
import org.linkerdesign.crypto.messagedigest.Sha256;
import org.linkerdesign.crypto.messagedigest.Sha384;
import org.linkerdesign.crypto.messagedigest.Sha512;

public class App {
	public static final String MSG = "《青溪》是唐代诗人王维创作的一首五言古诗。此诗描写了一条青溪的幽秀景色，诗人用多彩的画笔，绘出青溪流经不同地方时呈现的不同画面。其中“声喧乱石中，色静深松里”两句，以喧响的声音和幽冷的色调形成闹与静的强烈对比，如同一幅“有声画”。诗的末四句写出诗人心境的闲谈正如清川的闲淡，把自己的精神和自然的精神融和起来，意味隽永。全诗自然清淡素雅，写景抒情皆轻轻松松，然而韵味却隽永醇厚。诗人笔下的青溪是喧闹与沉郁的统一，活泼与安详的揉合，幽深与素静的融和。";

	public String getGreeting() {
		return "Hello World!";
	}

	public static void main(String[] args) {
		testMd();
		testAes();
		System.out.println(new App().getGreeting());
	}

	static void testMd() {
		var sha1 = new Sha1();
		var hash = sha1.digest(MSG, EncodingType.UTF8, EncodingType.Base64);
		out.println(String.format("%s:::%d", hash, hash.length()) );

		var sha256 = new Sha256();
		hash = sha256.digest(MSG, EncodingType.UTF8, EncodingType.Hex);
		out.println(String.format("%s:::%d", hash, hash.length()) );

		var sha384 = new Sha384();
		hash = sha384.digest(MSG, EncodingType.UTF8, EncodingType.Hex);
		out.println(String.format("%s:::%d", hash, hash.length()) );

		var sha512 = new Sha512();
		hash = sha512.digest(MSG, EncodingType.UTF8, EncodingType.Hex);
		out.println(String.format("%s:::%d", hash, hash.length()) );

		var md5 = new Md5();
		var hashWeb = "51dac0da1863951d696e027892bdc177";
		hash = md5.digest(MSG, EncodingType.UTF8, EncodingType.Hex);

		out.println(String.format("%s:::%d:::equals: %b", hash, hash.length(), hashWeb.equals(hash)));

		var md5Sha1 = new Md5Sha1();
		hash = md5Sha1.digest(MSG, EncodingType.UTF8, EncodingType.Hex);
		out.println(String.format("%s:::%d", hash, hash.length()) );
	}

	static void testAes() {
		Aes aes = new Aes();

    String key = aes.generateKey(AesKeySize.KS256, EncodingType.Base64);
    String iv = aes.generateIV(EncodingType.Base64);

    byte[] enc = aes.encrypt(key, iv, MSG, EncodingType.UTF8);
    String dec = aes.decrypt(key, iv, enc, EncodingType.UTF8);

		out.println(String.format("%s:::equals: %b", dec, MSG.equals(dec)));
	}
	
}
