/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_linkerdesign_crypto_Native */

#ifndef _Included_org_linkerdesign_crypto_Native
#define _Included_org_linkerdesign_crypto_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_linkerdesign_crypto_Native
 * Method:    digest
 * Signature: (IILorg/linkerdesign/crypto/ReadCallback;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_linkerdesign_crypto_Native_digest
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     org_linkerdesign_crypto_Native
 * Method:    generateAesKey
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_linkerdesign_crypto_Native_generateAesKey
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_linkerdesign_crypto_Native
 * Method:    generateAesIV
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_linkerdesign_crypto_Native_generateAesIV
  (JNIEnv *, jobject);

/*
 * Class:     org_linkerdesign_crypto_Native
 * Method:    aesEncrypt
 * Signature: (I[B[BILorg/linkerdesign/crypto/ReadCallback;Lorg/linkerdesign/crypto/WriteCallback;)I
 */
JNIEXPORT jint JNICALL Java_org_linkerdesign_crypto_Native_aesEncrypt
  (JNIEnv *, jobject, jint, jbyteArray, jbyteArray, jint, jobject, jobject);

/*
 * Class:     org_linkerdesign_crypto_Native
 * Method:    aesDecrypt
 * Signature: (I[B[BILorg/linkerdesign/crypto/ReadCallback;Lorg/linkerdesign/crypto/WriteCallback;)I
 */
JNIEXPORT jint JNICALL Java_org_linkerdesign_crypto_Native_aesDecrypt
  (JNIEnv *, jobject, jint, jbyteArray, jbyteArray, jint, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
